# Generated by Django 4.2.3 on 2023-07-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='date',
            new_name='time',
        ),
    ]
