# Generated by Django 4.2.3 on 2023-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_date_diary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
